export const FETCH_LABELS = 'FETCH_LABELS';
export const FETCH_LABELS_SUCCESS = 'FETCH_LABELS_SUCCESS';
export const FETCH_LABELS_FAILURE = 'FETCH_LABELS_FAILURE';
export const FETCH_LABELS_FINISHED = 'FETCH_LABELS_FINISHED';

export const FETCH_GLOBAL_DATA = 'FETCH_GLOBAL_DATA';
export const FETCH_GLOBAL_DATA_SUCCESS = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_FAILURE = 'FETCH_GLOBAL_DATA_FAILURE';
export const FETCH_GLOBAL_DATA_FINISHED = 'FETCH_GLOBAL_DATA_FINISHED';
export const FETCH_GLOBAL_DATA_FROM_INTERNET_SUCCESS = 'FETCH_GLOBAL_DATA_FROM_INTERNET_SUCCESS';
export const FETCH_GLOBAL_DATA_FROM_INTERNET_FAILURE = 'FETCH_GLOBAL_DATA_FROM_INTERNET_FAILURE';
export const FETCH_GLOBAL_DATA_FROM_INTERNET_FINISHED = 'FETCH_GLOBAL_DATA_FROM_INTERNET_FINISHED';
export const FETCH_GLOBAL_DATA_FROM_CACHE_SUCCESS = 'FETCH_GLOBAL_DATA_FROM_CACHE_SUCCESS';
export const FETCH_GLOBAL_DATA_FROM_CACHE_FAILURE = 'FETCH_GLOBAL_DATA_FROM_CACHE_FAILURE';
export const FETCH_GLOBAL_DATA_FROM_CACHE_FINISHED = 'FETCH_GLOBAL_DATA_FROM_CACHE_FINISHED';

export const FETCH_PER_COUNTRY_DATA = 'FETCH_PER_COUNTRY_DATA';
export const FETCH_PER_COUNTRY_DATA_SUCCESS = 'FETCH_PER_COUNTRY_DATA_SUCCESS';
export const FETCH_PER_COUNTRY_DATA_FAILURE = 'FETCH_PER_COUNTRY_DATA_FAILURE';
export const FETCH_PER_COUNTRY_DATA_FINISHED = 'FETCH_PER_COUNTRY_DATA_FINISHED';
export const FETCH_PER_COUNTRY_DATA_FROM_INTERNET_SUCCESS = 'FETCH_PER_COUNTRY_DATA_FROM_INTERNET_SUCCESS';
export const FETCH_PER_COUNTRY_DATA_FROM_INTERNET_FAILURE = 'FETCH_PER_COUNTRY_DATA_FROM_INTERNET_FAILURE';
export const FETCH_PER_COUNTRY_DATA_FROM_INTERNET_FINISHED = 'FETCH_PER_COUNTRY_DATA_FROM_INTERNET_FINISHED';
export const FETCH_PER_COUNTRY_DATA_FROM_CACHE_SUCCESS = 'FETCH_PER_COUNTRY_DATA_FROM_CACHE_SUCCESS';
export const FETCH_PER_COUNTRY_DATA_FROM_CACHE_FAILURE = 'FETCH_PER_COUNTRY_DATA_FROM_CACHE_FAILURE';
export const FETCH_PER_COUNTRY_DATA_FROM_CACHE_FINISHED = 'FETCH_PER_COUNTRY_DATA_FROM_CACHE_FINISHED';

export const FETCH_PER_COUNTRY_PER_DATE_DATA = 'FETCH_PER_COUNTRY_PER_DATE_DATA';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_SUCCESS = 'FETCH_PER_COUNTRY_PER_DATE_DATA_SUCCESS';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FAILURE = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FAILURE';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FINISHED = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FINISHED';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_SUCCESS = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_SUCCESS';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_FAILURE = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_FAILURE';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_FINISHED = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_INTERNET_FINISHED';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_SUCCESS = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_SUCCESS';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_FAILURE = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_FAILURE';
export const FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_FINISHED = 'FETCH_PER_COUNTRY_PER_DATE_DATA_FROM_CACHE_FINISHED';

export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_COUNTRY = 'SET_COUNTRY';